[env]
TERM = "xterm-256color"

[terminal]
osc52 = "CopyPaste"

[window]
opacity = 0.75
blur = true

[window.dimensions]
columns = 120
lines = 38

[keyboard]
bindings = []

[font]
size = 20.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[general]
import = [
  "~/.config/alacritty/themes/themes/cyber_punk_neon.toml"
]
